fix indentation

diff --git a/.github/workflows/aggregator.yml b/.github/workflows/aggregator.yml
--- a/.github/workflows/aggregator.yml
+++ b/.github/workflows/aggregator.yml
@@ -14,19 +14,19 @@ jobs:
     if: ${{ always() }}
     needs: ${{ fromJson(inputs.jobs) }}
     steps:
-        - name: Aggregate results
-          run: |
-            failed=()
-            for job in ${{ inputs.jobs }}; do
-              result=$(eval echo '${{ needs.'$job'.result }}')
-              if [ "$result" != "success" ]; then
-                failed+=("$job")
-              fi
-            done
-            
-            if [ ${#failed[@]} -ne 0 ]; then
-              echo "❌ Failed jobs: ${failed[*]}"
-              exit 1
+      - name: Aggregate results
+        run: |
+          failed=()
+          for job in ${{ inputs.jobs }}; do
+            result=$(eval echo '${{ needs.'$job'.result }}')
+            if [ "$result" != "success" ]; then
+              failed+=("$job")
             fi
+          done
             
-            echo "✅ All required jobs succeeded"
+          if [ ${#failed[@]} -ne 0 ]; then
+            echo "❌ Failed jobs: ${failed[*]}"
+            exit 1
+          fi
+            
+          echo "✅ All required jobs succeeded"
